// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ece4180.gpstracker.Models;

namespace web_code.Migrations
{
    [DbContext(typeof(TripContext))]
    partial class TripContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ece4180.gpstracker.Models.Location", b =>
                {
                    b.Property<int>("tripId");

                    b.Property<long>("timeStamp");

                    b.Property<double>("lat_");

                    b.Property<double>("long_");

                    b.HasKey("tripId", "timeStamp");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ece4180.gpstracker.Models.Trip", b =>
                {
                    b.Property<int>("tripId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("devicenum");

                    b.Property<long>("endTime");

                    b.Property<double>("end_lat_");

                    b.Property<double>("end_long_");

                    b.Property<long>("startTime");

                    b.Property<double>("start_lat_");

                    b.Property<double>("start_long_");

                    b.Property<int>("status");

                    b.HasKey("tripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("ece4180.gpstracker.Models.Location", b =>
                {
                    b.HasOne("ece4180.gpstracker.Models.Trip")
                        .WithMany("Locations")
                        .HasForeignKey("tripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
